services:
  redis:
    image: "redis:alpine"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  mlserver:
    build: .
    container_name: mlserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis